### PR TITLE
Lots of cleanup

### PR DESCRIPTION
**Pull request by jdogcoder**
# Pull Request

Severe cleanup, adds linter

## Related Issue:

Closes #XXXXX

### CODE REVIEW

**Review by aramshiva — CHANGES_REQUESTED** [review]
What if [ESLint GIthub Action](https://github.com/marketplace/actions/action-eslint) to ensure linter runs on all pull requests?

**Comment by jdogcoder** [comment]
I am using commit hooks locally, that should install on clone, we can add that tho if you want.

**Comment by aramshiva** [comment]
Adding Now!

**Comment by jdogcoder** [comment]
lol we both got to it :)

**Review by aramshiva — APPROVED** [review]

**Comment by aramshiva** [comment]
lg!

**Comment by aramshiva** [comment]
hmm some issues. gonna remove function for now.

**Comment by jdogcoder** [comment]
This is good to merge now yea? or....

**Comment by aramshiva** [comment]
yup!

**Comment by jdogcoder** [comment]
Can you approve it lol?

**Comment by jdogcoder** [comment]
It won't let me caus it's my PR -_-

**Comment by aramshiva** [comment]
dosent let me either cause I contributed!

**Pull request merged**
