### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by jdogcoder**
# Pull Request

## Related Issue:

Closes #XXXXX

### CODE REVIEW

**Comment by jdogcoder** [comment]
@thepurplebubble/website plz review

**Review by CaenJones — APPROVED** [review]

**Comment by kcoderhtml** [comment]
lgtm! can't figure out how to review it though

**Comment by kcoderhtml** [comment]
The vercel integration needs to be removed.

**Comment by jdogcoder** [comment]
oh lol I see it

**Comment by jdogcoder** [comment]
I think I may need to admin override this one...

**Pull request merged**
