### PR TITLE
Brand page

### PR DESCRIPTION
**Pull request by polypixeldev**
# Pull Request

## Description:

Adds a new page called brand that shows our logo, colors, and fonts. Fixes some styling & formatting issues as well.

> Still WIP as the assets and colors themselves are still being finalized.

### CODE REVIEW

**Comment by jdogcoder** [comment]
@polypixeldev looks good. Will do a full review when I recover my laptop tomorrow.

**Comment by jdogcoder** [comment]
@polypixeldev is this also the cdn.purplebubble? Or is that coming separately?

**Comment by jdogcoder** [comment]
Can we have /branding also work (redirect to /brand)

**Comment by jdogcoder** [comment]
Would also love to see some background, either a gradient or graphic to make the page a bit nicer looking.

**Comment by jdogcoder** [comment]
Overall it looks great.

**Comment by jdogcoder** [comment]
Also think we should settle on a typeface as a group.

**Comment by polypixeldev** [comment]
> @polypixeldev is this also the cdn.purplebubble? Or is that coming separately?

I mean the assets will be available on the website, for example https://purplebubble.org/logo.png. Do we need more than that?

**Comment by polypixeldev** [comment]
I believe it was line 311 of style.css - an absolute path wasn't used. It's fixed in my PR #22, so feel free to merge this one!

**Review by jdogcoder — APPROVED** [review]

**Pull request merged**
