### PR TITLE
Update with new branding slogan

### PR DESCRIPTION
**Pull request by jdogcoder**
# Pull Request

## Related Issue:

Closes #XXXXX

### CODE REVIEW

**Review by kcoderhtml — DISMISSED** [review]
lgtm!

**Comment by kcoderhtml** [comment]
no period though? its a stylistic choice so your call

**Comment by jdogcoder** [comment]
no lol it needs it

**Comment by jdogcoder** [comment]
I also didn't update the actual text yet hold on

**Review by kcoderhtml — APPROVED** [review]

**Pull request merged**
