### PR TITLE
Major Changes In Look and Feel of Site

### PR DESCRIPTION
**Pull request by ghost**
This Draft Changes The Following

- Changes Header Image
- Adds animations in the text sections
- Creates Meta Tags
- Changes General Color and Theme (purple and black)

### CODE REVIEW

**Comment by jdogcoder** [comment]
Will take a look now.

@CaenJones feel free to also work on a branch, you should have branch permissions.

**Comment by jdogcoder** [comment]
#4 partially worked on here. (NOT CLOSED THO)

**Review by jaspermayone — APPROVED** [review]
Looks super good!

**Comment by CaenJones** [comment]
Thank you very much!

**Pull request merged**
